[package]
name = "smeagol-cli"
version = "0.1.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
smeagol = { path = "../smeagol" }

[dev-dependencies]
assert_cmd = "0.11"

[[bin]]
name = "smeagol"
path = "src/main.rs"
