var ALIASES = {};
ALIASES["either"] = {};
ALIASES["proc_macro2"] = {};
ALIASES["quote"] = {};
ALIASES["smeagol"] = {};
ALIASES["syn"] = {};
ALIASES["thiserror"] = {};
ALIASES["thiserror_impl"] = {};
ALIASES["unicode_xid"] = {};
