[package]
name = "smeagol"
version = "0.2.0-alpha"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
description = "Conway's Game of Life using HashLife and SIMD."
repository = "https://github.com/billyrieger/smeagol"
readme = "README.md"
keywords = ["life", "conway", "cellular", "automaton", "hashlife"]
categories = ["algorithms", "science", "simulation"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
derive_more = "0.99.11"
generational-arena = "0.2.8"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }

[dev-dependencies]