[package]
name = "smeagol"
version = "0.5.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
edition = "2018"
publish = false

[dependencies]

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "bench"
harness = false
