[package]
name = "smeagol"
version = "0.2.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
description = "Efficient simulation of Life-like cellular automata"
repository = "https://github.com/billyrieger/smeagol"
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
publish = false

[dependencies]
generational-arena = "0.2.8"
packed_simd = "0.3.3"
