[package]
name = "smeagol"
version = "0.2.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
license = "MPL-2.0"
edition = "2018"

readme = "README.md"
repository = "https://github.com/billyrieger/smeagol"

publish = false

[dependencies]
