[package]
name = "smeagol"
version = "0.1.1"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
description = "A library to efficiently simulate Conway's Game of Life using the HashLife algorithm."
repository = "https://github.com/billyrieger/smeagol"
readme = "README.md"
keywords = ["life", "conway", "cellular", "automaton", "hashlife"]
categories = ["algorithms", "science", "simulation"]
license = "MPL-2.0"
edition = "2018"

[badges]
codecov = { repository = "billyrieger/smeagol" }
travis-ci = { repository = "billyrieger/smeagol" }

[dependencies]
btoi = "0.4"
failure = "0.1"
hashbrown = "0.1"
nom = "4.2"
packed_simd = "0.3"
png = "0.14"

[dev-dependencies]
criterion = "0.2"
version-sync = "0.7"

[[bench]]
name = "bench"
harness = false
