[package]
name = "smeagol"
version = "0.5.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
description = "Conway's Game of Life using HashLife and SIMD."
repository = "https://github.com/billyrieger/smeagol"
readme = "README.md"
keywords = ["life", "conway", "cellular", "automaton", "hashlife"]
categories = ["algorithms", "science", "simulation"]
license = "MPL-2.0"
edition = "2018"
