[package]
name = "smeagol"
version = "0.2.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
description = "TODO"
repository = "https://github.com/billyrieger/smeagol"
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
publish = false

[dependencies]
either = "1.5.3"
thiserror = "1.0.16"
